import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // console.log(styles);
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjx, huntingcoder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      
      {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}
      <main className={styles.main}>
      <div className={styles.imagewrap}>
        {/* <Image className={styles.myImg} src='/homeimg.avif' width={237} height={158} /> */}
        <img className={styles.myImg} src='/homeimg.avif' width={237} height={158} alt='hunting coder' />
        </div>
        <div className={styles.description}>
        </div>
        <div className={styles.center}>
         <h1 className={styles.title}><span className='dummy'>&lt;Hunting Coder/&gt;</span></h1> 
        </div>
  
        {/* <p>A Blog for the hunting coder by a hunting coder. This blog is about to learning programming and the other tools of development. The blog is guide us about how the programming works and how to develop your logical skills.</p> */}
        {/* <div className={`${styles1.con} ${styles2.con}`}> */}
          <div>
          <h2 className={styles.h2}>Latest Blogs</h2>
               <div>
                 <h3 className={styles.h3}>How to learn Javascript in 2022?</h3>
                 <p>Javascript is the language used to design logic for the web. And Javascript learn you about to build a website and boost your logical skills.</p>
                 <button className={styles.btn}>Read More</button>
               </div>
               <div>
                 <h3 className={styles.h3}>How to learn Javascript in 2022?</h3>
                 <p className={styles.p}>Javascript is the language used to design logic for the web.</p>
                 <button className={styles.btn}>Read More</button>
               </div>
               <div>
                 <h3 className={styles.h3}>How to learn Javascript in 2022?</h3>
                 <p>Javascript is the language used to design logic for the web.</p>
                 <button className={styles.btn}>Read More</button>
               </div>
            </div>
      

        
      </main>
    </>
  )
}
